sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        UYmkZ6q8SAZf21iQ22tlVj+E8dwjZQbkELxSrMvwV9Wu5dGGOvFR0WDRs0A330cxEqZBVvjOt8HcagZ2/DKEZVcMDIIjZlCJeelGxSUd5hSQ4/KQWKvBM661N3d1oEWnosdl6wX1FAPs4OOiMmYaIzpuTIsvsTX5eMQCw45wE3JngJLYybo/5Z0v/ArrVdFd3j+10nJ9+wBaWQpVE2PlybNTQDt0DG2MDJ+Q9oeStGiTrGUr1GU2I0rUKK8THOlVxyZg37jrg/g8yPqWBLXwdnI0nsI9X78OlIWKbn3XcEi25ql7oQqW1AcBN2x/qL9IxyBN95WvPv8VVwfp25fU6cAJPpdZ/rXeC5uOdleXhPE3XCPjoCB0pfOprBkfz2gU3+XrMaZ2CZSDX1Mzg9uqqdUKysd+CKADZsrIuM7Y1bck7w5lVd5Rm0jsg70n/PXXLLm/rG1unOJ4QY9XdDmoP01STSGTnAdpYanSiIwzlkMGSIB7chkUhmHypqNd7zVsXNYfRYWbFr1fp+xt/pilmJmVAETWX2M10bYIF9mHcXrwC5dEYHs0kU4YsJkNC+/kCPIBWq44S4Wf2rjcu+sTqDNJDndGnnwf4ZN5ItoRcwEnENd9het0JMntXzjSDfIXX8ZCybVZo731JKvNc9P8a90tVP6/l17N43UH5EB93II=
    - secure: >-
        HZeTEAJ6aC5qSHKE1QtxNkMDtm9eL7xw+OXWYU/MfGVheqIl/KyGba0UFPiYUfXq+73QveAl368Ut3BOtANYWYEe6SQTkjeYyG2td+lZP8xuDw/rCzyugpmn6PT5tGUwrIgb6niYNWRoUvzn1GniUPHYjzUIZBHIwwwsc0MMvKaIgNrIepAm5LSfEUxPvwqtb/1ndwpQuiYVRtzHlu90JxBEM/Gagoj8UjLPpFcrCLTHJcb3b0o99e3CfXnojdcwvVtwwo/OBMQmeYZkEr7cOVGRweHOsT8jRoweJXM0B+aYH7P+ML2QudchhO7lYp7OS108aKnc5a/2W9XzPAG/cq9lPfNFGBNmVZoaIlTEoamiKZenPDvlq06Rxk51GEFnFdpt/lRvi9qcJkTCGM4SJcGDMzS8GDrfjH/jqbNtWr3swql50skzoBEhnoIPHONldZqgqJVpKaaS/lmg5EUbEGIhLvxC5/30SbLXX5OqvUa3OEvTE0CyP6Iw5rFXomHqwQqiOmeV4SYwUb5m0OifQwE2S5JYb7w3jPY222D71n1kAnnnaRhMM9nxsVhxS233+ojGxg9izKvreabYaKPgu41GQ8pR3qylU0pPanxjGTNmQ07USYcb9UJzQuE3zRzMnfiAb+fGX4ZBYvoG6VHI6Rkl6KO4ayrPPGmadI3Xmk4=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
